name: grow_it_green
description: An app to help with gardening.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cache:
    path: packages/cache
  equatable: ^2.0.5
  firebase_core: ^2.9.0
  firebase_database: ^10.1.0
  flutter:
    sdk: flutter
  formz: ^0.4.1
  http: ^0.13.5
  intl: ^0.18.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^2.0.1
  flutter_launcher_icons: ^0.12.0

#   flutter_launcher_icons: "^0.13.1"
flutter_icons:
  image_path: "assets/images/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # background_color_ios: "#ffffff"
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/icon.png"
#   min_sdk_android: 19 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/images/products/
    # - assets/images/services/
    # - assets/images/encyclopedias/

  # assets:
  #   - assets/images/logo.png
  #   - assets/images/onboarding1.png
  #   - assets/images/onboarding2.png
  #   - assets/images/onboarding3.png
  #   - assets/images/man.png
  #   - assets/images/products/1.png
  #   - assets/images/products/2.png
  #   - assets/images/products/3.png
  #   - assets/images/services/1.png
  #   - assets/images/services/2.png
  #   - assets/images/services/3.png
  #   - assets/images/encyclopedias/1.png
  #   - assets/images/encyclopedias/2.png
  #   - assets/images/encyclopedias/3.png
